# Deep Learning Course - Requisites Exercises

This is a Jupyter Notebook containing exercises to test the requisites for the IA368Z course that will be offered in the second semester of 2017.

### Python

Use Python 3.6 while solving the exercises. We recommend [Anaconda](https://www.continuum.io/downloads) - a Data Science focused python distribution.

### Tools

This is a Jupyter Notebook. If you never used one, a Jupyter notebook is a mix of Markdown (like a Wiki) and a Python program. It is very popular among people working with Data Science and Machine Learning in Python. If you need some help on how to use Jupyter Notebooks, please take a look at this [beginner-guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/).

You are free to add as many cells as you want to this notebook in order to make your work readable and well organized.

# Basic Exercises
Let's begin! Start by printing your name and e-mail here:

In [1]:
# fill in your data
print('My name is Raphael Voltoline Ramos')
print('My email is raphavoltoline.rvr@gmail.com')

My name is Raphael Voltoline Ramos
My email is raphavoltoline.rvr@gmail.com


## Lists

The following are list exercises. For those that do not have experience with Python, we recommend
using these exercises do learn more about the subject related to the exercise.

In [50]:
mylist = [5, 8, 'abc', 0, 8.3]

### Print the number of elements of the list `mylist`

In [31]:
print ('The number of elements:', len(mylist))

Number of elements: 5


### This is list a

In [2]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
print(a[3:5])

[3, 4]


In [45]:
# print the odd elements of list a:
print ('The odd elements:', a[1::2])

The odd elements: [1, 3, 5, 7, 9]


In [46]:
# print the even elements of list a:
print ('The even elements:', a[0::2])

The even elements: [0, 2, 4, 6, 8]


In [47]:
# print the last 3 elements of the list a:
print ('The last 3 elements:', a[-3:])

The last 3 elements: [7, 8, 9]


In [3]:
# print the first 3 elements of the list a:
print ('The first 3 elements:', a[:3])

The first 3 elements: [0, 1, 2]


In [8]:
print(a[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [118]:
# print the odd elements of list a, from the largest to the smallest
print ('The odd elements (descending order):', a[-1:0:-2])

The odd elements (descending order): [9, 7, 5, 3, 1]


## Tuples

In [22]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


The main difference between a list and a tuple is that tuple is immutable.

# Exercises with NumPy

The following exercises should use only NumPy operations.
Avoid import other packages

In [23]:
import numpy as np

In [24]:
A = np.arange(8,8+24).reshape(4,6)
print(A)

[[ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]
 [26 27 28 29 30 31]]


### rows, cols, dimensions, shape and datatype

In [119]:
# print the number of rows of A:
print('The number of rows of A:', A.shape[0])

The number of rows of A: 4


In [120]:
# print the number of cols of A:
print('The number of cols of A:', A.shape[1])

The number of cols of A: 6


In [121]:
# print the number of dimensions of A:
print('The number of dimensions of A:', A.ndim)

The number of dimensions of A: 2


In [122]:
# print the shape of A:
print('The shape of A:', A.shape)

The shape of A: (4, 6)


In [123]:
# print the datatype of the elements of A
print('The datatype of A:', A.dtype)

The datatype of A: int32


### Boolean array

In [39]:
# create a boolean matrix B with True if the element of A is less than 15 (without using a loop)
B = A < 15 # <<modify your code here
print(B)

[[ True  True  True  True  True  True]
 [ True False False False False False]
 [False False False False False False]
 [False False False False False False]]


### Axis reduction: sum

In [16]:
print(A.sum(axis=0))

[68 72 76 80 84 88]


In [124]:
# what is the number of dimensions of the array C = A.sum(axis=0)?
C = A.sum(axis=0)
print('The number of dimensions of C is:', C.ndim)

The number of dimensions of C is: 1


In [44]:
# compute the mean value of the array A
print('The mean of A:', A.mean())

The mean of A: 19.5


In [64]:
# create a matrix C that is a normalization of A, so that its value are between 0.0 and 1.0
C = A / A.max()
print('Normalization of A')
print(C)

Normalization of A
[[ 0.25806452  0.29032258  0.32258065  0.35483871  0.38709677  0.41935484]
 [ 0.4516129   0.48387097  0.51612903  0.5483871   0.58064516  0.61290323]
 [ 0.64516129  0.67741935  0.70967742  0.74193548  0.77419355  0.80645161]
 [ 0.83870968  0.87096774  0.90322581  0.93548387  0.96774194  1.        ]]


In [65]:
# create a matrix D that is a nomalization of the columns of A, so that each column of D has values between 0. and 1.
D = A / A.max(axis=0)
print('Normalization per column of A')
print(D)

Normalization per column of A
[[ 0.30769231  0.33333333  0.35714286  0.37931034  0.4         0.41935484]
 [ 0.53846154  0.55555556  0.57142857  0.5862069   0.6         0.61290323]
 [ 0.76923077  0.77777778  0.78571429  0.79310345  0.8         0.80645161]
 [ 1.          1.          1.          1.          1.          1.        ]]


### Slicing

In [20]:
# this operation is called slicing:
AA = A[:,1::2]
print(AA)

[[ 9 11 13]
 [15 17 19]
 [21 23 25]
 [27 29 31]]


In [125]:
# create matrix AB with the odd rows of matrix A, using the concept of slicing:
AB = A[1::2, :]
print('The odd rows of A')
print(AB)

The odd rows of A
[[14 15 16 17 18 19]
 [26 27 28 29 30 31]]


### Matrix dot product

In [126]:
# create a matriz AC which is a rotation of 90 degrees anti-clockwise of the matrix A
AC = np.rot90(A)
print('Rotation of 90 degrees anti-clockwise of A')
print(AC)

Rotation of 90 degrees anti-clockwise of A
[[13 19 25 31]
 [12 18 24 30]
 [11 17 23 29]
 [10 16 22 28]
 [ 9 15 21 27]
 [ 8 14 20 26]]


Compute $$ E = A A^T $$

In [76]:
E = np.dot(A, A.transpose()) # modify your code here
print('Matrix multiplication')
print(E)

Matrix multiplication
[[ 679 1057 1435 1813]
 [1057 1651 2245 2839]
 [1435 2245 3055 3865]
 [1813 2839 3865 4891]]


### 3-D array

In [78]:
F = A.reshape(2,4,3)
print(F)

[[[ 8  9 10]
  [11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]
  [29 30 31]]]


In [81]:
# print the number of dimensions of F
print('The number of dimensions of F:', F.ndim)

The number of dimensions of F: 3


In [82]:
# print the shape of F
print('The shape of F:', F.shape)

The shape of F: (2, 4, 3)


In [135]:
# compute the mean value of the two matrices F[0] and F[1], using a single command using F.mean(??)
print('The mean value of the two matrices')
print(F.mean(axis=(2,1)))

The mean value of the two matrices
[ 13.5  25.5]


In [95]:
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


### Broadcasting

- What is the concept of broadcasting in NumPy?
- Answer: The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes [https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html].

In [96]:
# Using the concept of broadcasting, create matrix G with the sum of vector v to every column of A:
G = A + v.reshape(4, 1)
print('Using broadcasting to sum a vector and a matrix')
print(G)

Using broadcasting to sum a vector and a matrix
[[ 9 10 11 12 13 14]
 [16 17 18 19 20 21]
 [23 24 25 26 27 28]
 [30 31 32 33 34 35]]


### Function - one-hot encoding

Define a function that receives as input an one-dimensional array and the output a one-hot encoding
following the example:

In [97]:
# input
aa = np.array([2,0,3,2,1])
print(aa)

[2 0 3 2 1]


In [98]:
# output
oo = np.array([[0,0,1,0],
               [1,0,0,0],
               [0,0,0,1],
               [0,0,1,0],
               [0,1,0,0]])
print(oo)

[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [115]:
# Try to avoid explicit loop as much as possible
# Use only NumPy operations, no other libraries
def one_hot(i):
    # insert your code here
    oo = np.zeros((i.shape[0], i.max() + 1));
    oo[np.arange(0, i.shape[0]), i] = 1
    return oo

print('one-hot encoding')

print('test #00')
print(one_hot(aa))

# test with other vectors
print('\ntest #01')
print(one_hot(np.array([0, 3, 6, 2, 8, 15, 2, 6])))

print('\ntest #02')
print(one_hot(np.array([6, 2, 3, 5, 4, 8, 5, 1, 1, 2, 6, 6])))

one-hot encoding
test #00
[[ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]]

test #01
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

test #02
[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.

# The end